### PR TITLE
Feat: Handle mini music player like spotify

### PR DESCRIPTION
**Pull request by Shreyassp002**
This pull request introduces the following changes to enhance the mini music player:

- **Persistent Mini Player:** The mini music player remains visible even when the song is paused.
- **Dynamic Background:** Background color now adapts to the poster using the Palette library.
- **Custom Seekbar:** Implemented a custom seekbar for better user experience.
- **Dependency Update:** Added the Palette library for dynamic color extraction.

**Screenshots-**
<p align="center">
  Screenshot 1
  Screenshot 2
</p>

**Issue Link:** [MOBILE-209](https://tickets.metabrainz.org/browse/MOBILE-209)

Let me know if any changes are required :)

### CODE REVIEW

**Comment by 07jasjeet** [comment]
Really exciting PR @Shreyassp002. Can you also fix the seek bar inside of the player screen as well while you're at it? I'm very pleased with your implementation!

**Comment by Shreyassp002** [comment]
@07jasjeet Thanks! I’m on it and will fix the seek bar.

**Comment by Shreyassp002** [comment]
@07jasjeet Fixed seekbar for PlayerScreen 

photo_2024-12-27_19-59-31

**Review by 07jasjeet — APPROVED** [review]
LGTM, Great work!

**Comment by 07jasjeet** [comment]
Thanks for the contribution @Shreyassp002!

**Pull request merged**
