### PR TITLE
Feat: Added Profile Page for the User

### PR DESCRIPTION
**Pull request by rishuriya**
There is a component of an App which work with login is a profile page of a user who is using the app, So i tried to create a simple profile page for the Listenbrainz-android, The profile photo on the top center which user can choose, a percentage circular chart surround the image as its border which indicate total completion of profile. In content of profile, i made a change in api and added email in scope as written in documentation of musicbrainz api. The Average time spent is coming directly from mobile phone for that i need to add a permission in manifest. apart from that I am not able to get Name from api because musicbrainz didnt ask for name. so i made a Cache where user name will be save, apart from that profile photo also save in cache with help of bitmap. There are other cards such as total music listen, favorite Singer, Follow and follower. Out of 4, i will make 2 of it functional by end of this week. The screenshot and a video is attach below
Screenshot from 2023-02-12 07-03-52

https://user-images.githubusercontent.com/85174423/218288583-a361130c-8d5a-460c-b8c5-937d8401e95d.mp4

@akshaaatt bhaiya please review it, if any immediate changes required in this please mention

### CODE REVIEW

**Comment by 07jasjeet** [comment]
Hey! Great work. Please have a discussion with me and @akshaaatt on #metabrainz channel. If you feel stuck take look at the communication section of this doc: https://docs.google.com/document/d/1hY5oloIiANeXg1R9oSBIr2ZUHSlm7LU8qy6tW1VJMQg/edit

**Comment by rishuriya** [comment]
thanks @07jasjeet for reminding but right now i am bit occupied with my end semester and Adding some left stuff in profile, once i am done with adding all that i will surely discuss with @akshaaatt , i have given myself the deadline of Wednesday. so i am just trying to add all these stuff till that time.

**Comment by rishuriya** [comment]
@akshaaatt bhaiya, As i said i will add code to display value of two card on basis of user, Which is now added. Now user can see Their favorite artist and total song listen. Favorite artist is on the basis of most frequent artist from recently played. 

can you review it and if everything is good can you merge it too.

**Comment by akshaaatt** [comment]
As we discussed on IRC, this PR has a lot of irrelevant additions. Please discuss with us for further updates but this PR is huge and I don't believe it can be corrected easily. It would be better if we create a new implementation of this feature in a new branch and PR.

**Pull request closed without merging**
