### PR TITLE
Theme fixed

### PR DESCRIPTION
**Pull request by SB2318**
https://user-images.githubusercontent.com/87614560/228992955-91722ea8-d8e8-455e-8ebe-5e087ed63eed.mp4

@akshaaatt please review

### CODE REVIEW

**Comment by SB2318** [comment]
> Usually this means that the user loses state that they were in before switching the theme. I would recommend you to try out what reddit does on their android app. I'm pretty sure they use compose and take a little different approach. But, if not possible, this can also be accepted as an approach.

Okay, will try. Thanks for the info 😇

**Comment by 07jasjeet** [comment]
> @07jasjeet If you don't mind Can you please send me a recording, at least 10s.
> 
> I didn't get what is the difference in reddit. 
> 
> 
> 
> get it, will try

Don't worry btw this is prolly going to be merged, I just recommend you to look into improving this in further iterations :)

**Comment by SB2318** [comment]
> > @07jasjeet If you don't mind Can you please send me a recording, at least 10s.
> > I didn't get what is the difference in reddit.
> > get it, will try
> 
> Don't worry btw this is prolly going to be merged, I just recommend you to look into improving this in further iterations :)

Thank you, actually for this I need some time. 😅
But will try

**Review by akshaaatt — APPROVED** [review]
LGTM! Thanks 💯

**Pull request merged**
