### PR TITLE
MOBILE-192: Sort Collections by Name/Title by Default

### PR DESCRIPTION
**Pull request by tmose1106**
As per [MOBILE-192](https://tickets.metabrainz.org/browse/MOBILE-192) the collections in the player were not sorted in any way. I have made the following changes to make this experience more usable and consistent:

- Added `ORDER BY` clauses to the DOAs for the problematic collections. This provides a sane default sorting by name/title.
- Removed the additional sorting from the `SongScreen` so that the list on the `BrainzPlayerScreen` and `SongScreen` are consistent, as with the other collection screens.

### CODE REVIEW

**Comment by pranavkonidena** [comment]
@tmose1106 Please don't open any PR's directly to main, please update the base branch in your PR to dev. Thanks for opening the PR!

**Comment by tmose1106** [comment]
I have now re-pointed the pull request towards the `dev` branch.

**Comment by 07jasjeet** [comment]
@akshaaatt

**Review by akshaaatt — APPROVED** [review]
Looks fine after testing. Thanks

**Pull request merged**
