### PR TITLE
kapt to ksp migration (Work in Progress)

### PR DESCRIPTION
**Pull request by utkarsh006**
- Solves #330

### CODE REVIEW

**Review by akshaaatt — COMMENTED** [review]
Why was this required? Also, what are the benefits this brings? I could have just given this file to an LLM and asked it to convert for me.

**Comment by utkarsh006** [comment]
@akshaaatt What's LLM? The issue is mentioned in PR and the purpose is mentioned [here](https://tickets.metabrainz.org/browse/MOBILE-183)

**Comment by akshaaatt** [comment]
@utkarsh006 My statements were clear, and your comprehension deviates markedly from the intended message. We operate on a principle that requires logical reasoning behind every action. If you are keen on contributing, it is imperative that you first focus on the tickets we have prepared. I strongly advise initiating a conversation with us on IRC before taking any steps.

**Comment by utkarsh006** [comment]
@akshaaatt Cool akshat, your statements were clear, so I deviated and yes I responded the same way, your tone of reply was to me. I would suggest you being simple with your words with the future contributors.

**Pull request closed without merging**
