### PR TITLE
Fix: don't fetch cover art urls twice

### PR DESCRIPTION
**Pull request by prabalsingh24**

### CODE REVIEW

**Comment by prabalsingh24** [comment]
@akshaaatt this makes sense right? we're already fetching urls while fetching the listens. No need to make the API call again

**Review by akshaaatt — APPROVED** [review]
Great point. This seems to have been missed out. Thanks a lot for looking into this and fixing 💯

**Comment by 07jasjeet** [comment]
This flow was used to give pre-loader URLs to work with. Since the pre loader is now removed, might as well get rid of the coverArtFlow as well and use the function as is.

**Comment by akshaaatt** [comment]
@07jasjeet that sounds right to me. I think removing the flow would be the better option here @prabalsingh24 since it involves storing things separately and then accessing them via index.

**Comment by akshaaatt** [comment]
For now, this is correct and I don't wanna burden the PR with optimizations because this fix is important.

**Pull request merged**
